In [1]:
import fastf1
import pandas as pd
import numpy as np
from pathlib import Path

print(fastf1.__version__)

3.8.1

In [2]:
# Set up cache
Path('../fastf1_cache').mkdir(exist_ok=True)
fastf1.Cache.enable_cache('../fastf1_cache')

In [3]:
# Check which races are available
fastf1.get_event_schedule(2026)[['Country', 'Location', 'EventName']]

                 Country           Location                 EventName
0                Bahrain            Bahrain        Pre-Season Testing
1                Bahrain            Bahrain        Pre-Season Testing
2              Australia          Melbourne     Australian Grand Prix
3                  China           Shanghai        Chinese Grand Prix
4                  Japan             Suzuka       Japanese Grand Prix
5          United States      Miami Gardens          Miami Grand Prix
6                 Canada           Montréal       Canadian Grand Prix
7                 Monaco        Monte Carlo         Monaco Grand Prix
8                  Spain          Barcelona      Barcelona Grand Prix
9                Austria          Spielberg       Austrian Grand Prix
10        United Kingdom        Silverstone        British Grand Prix
11               Belgium  Spa-Francorchamps        Belgian Grand Prix
12               Hungary           Budapest      Hungarian Grand Prix
13           Netherlands          Zandvoort          Dutch Grand Prix
14                 Italy              Monza        Italian Grand Prix
15                 Spain             Madrid        Spanish Grand Prix
16            Azerbaijan               Baku     Azerbaijan Grand Prix
17             Singapore         Marina Bay      Singapore Grand Prix
18         United States             Austin  United States Grand Prix
19                Mexico        Mexico City    Mexico City Grand Prix
20                Brazil          São Paulo      São Paulo Grand Prix
21         United States          Las Vegas      Las Vegas Grand Prix
22                 Qatar             Lusail          Qatar Grand Prix
23  United Arab Emirates         Yas Marina      Abu Dhabi Grand Prix

In [4]:
# Load session
session = fastf1.get_session(2026, 'Australia', 'Q')
session.load()

core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 18
core        WARNING 	No lap data for driver 55
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 18)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 55)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '6', '16', '81', '1', '44', '30', '41', '5', '27', '87', '31', '10', '23', '43', '14', '11', '77', '18', '3', '55']

In [5]:
# Session type
print(type(session))

# Event name
print(session.event['EventName'])

# Session name
print(session.name)

# Laps dataframe
session.laps.head()

# Column names
session.laps.columns.tolist()

<class 'fastf1.core.Session'>
Australian Grand Prix
Qualifying

['Time',
 'Driver',
 'DriverNumber',
 'LapTime',
 'LapNumber',
 'Stint',
 'PitOutTime',
 'PitInTime',
 'Sector1Time',
 'Sector2Time',
 'Sector3Time',
 'Sector1SessionTime',
 'Sector2SessionTime',
 'Sector3SessionTime',
 'SpeedI1',
 'SpeedI2',
 'SpeedFL',
 'SpeedST',
 'IsPersonalBest',
 'Compound',
 'TyreLife',
 'FreshTyre',
 'Team',
 'LapStartTime',
 'LapStartDate',
 'TrackStatus',
 'Position',
 'Deleted',
 'DeletedReason',
 'FastF1Generated',
 'IsAccurate']

In [6]:
session.laps['Driver'].unique()

array(['RUS', 'ANT', 'HAD', 'LEC', 'PIA', 'NOR', 'HAM', 'LAW', 'LIN',
       'BOR', 'HUL', 'BEA', 'OCO', 'GAS', 'ALB', 'COL', 'ALO', 'PER',
       'BOT', 'VER'], dtype=object)

In [7]:
# This is the method name to use is loaders.py
session.laps.pick_drivers('ANT')

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
22,0 days 00:34:49.014000,ANT,12,0 days 00:01:59.979000,1.0,1.0,0 days 00:33:06.451000,NaT,0 days 00:00:57.486000,0 days 00:00:20.671000,...,True,Mercedes,0 days 00:33:06.451000,2026-03-07 05:20:25.163,1,NaN,False,,False,False
23,0 days 00:36:09.134000,ANT,12,0 days 00:01:20.120000,2.0,1.0,NaT,NaT,0 days 00:00:28.214000,0 days 00:00:17.610000,...,True,Mercedes,0 days 00:34:49.014000,2026-03-07 05:22:07.726,1,NaN,False,,False,True
24,0 days 00:37:57.628000,ANT,12,0 days 00:01:48.494000,3.0,1.0,NaT,NaT,0 days 00:00:35.026000,0 days 00:00:24.129000,...,True,Mercedes,0 days 00:36:09.134000,2026-03-07 05:23:27.846,1,NaN,False,,False,True
25,0 days 00:39:17.917000,ANT,12,0 days 00:01:20.289000,4.0,1.0,NaT,NaT,0 days 00:00:28.414000,0 days 00:00:17.745000,...,True,Mercedes,0 days 00:37:57.628000,2026-03-07 05:25:16.340,1,NaN,False,,False,True
26,0 days 00:48:02.851000,ANT,12,NaT,5.0,1.0,NaT,0 days 00:40:54.685000,0 days 00:00:33.419000,0 days 00:00:21.126000,...,True,Mercedes,0 days 00:39:17.917000,2026-03-07 05:26:36.629,12,NaN,False,,False,False
27,0 days 00:50:04.906000,ANT,12,0 days 00:02:02.055000,6.0,2.0,0 days 00:48:19.626000,NaT,0 days 00:00:59.750000,0 days 00:00:19.667000,...,True,Mercedes,0 days 00:48:02.851000,2026-03-07 05:35:21.563,1,NaN,False,,False,False
28,0 days 00:51:24.510000,ANT,12,0 days 00:01:19.604000,7.0,2.0,NaT,NaT,0 days 00:00:27.908000,0 days 00:00:17.495000,...,True,Mercedes,0 days 00:50:04.906000,2026-03-07 05:37:23.618,1,NaN,False,,False,True
29,0 days 00:55:53.586000,ANT,12,NaT,8.0,2.0,NaT,0 days 00:53:09.374000,0 days 00:00:36.062000,0 days 00:00:23.975000,...,True,Mercedes,0 days 00:51:24.510000,2026-03-07 05:38:43.222,1,NaN,False,,False,False
30,0 days 00:57:35.793000,ANT,12,0 days 00:01:42.207000,9.0,3.0,0 days 00:55:56.888000,NaT,0 days 00:00:42.908000,0 days 00:00:19.645000,...,False,Mercedes,0 days 00:55:53.586000,2026-03-07 05:43:12.298,1,NaN,False,,False,False
31,0 days 00:58:55.228000,ANT,12,0 days 00:01:19.435000,10.0,3.0,NaT,NaT,0 days 00:00:28.002000,0 days 00:00:17.497000,...,False,Mercedes,0 days 00:57:35.793000,2026-03-07 05:44:54.505,1,NaN,False,,False,True
32,0 days 01:12:27.734000,ANT,12,NaT,11.0,3.0,NaT,0 days 01:00:41.123000,0 days 00:00:42.834000,0 days 00:00:21.402000,...,False,Mercedes,0 days 00:58:55.228000,2026-03-07 05:46:13.940,12,NaN,False,,False,False
33,0 days 01:14:10.463000,ANT,12,0 days 00:01:42.729000,12.0,4.0,0 days 01:12:30.463000,NaT,0 days 00:00:41.705000,0 days 00:00:19.802000,...,True,Mercedes,0 days 01:12:27.734000,2026-03-07 05:59:46.446,1,NaN,False,,False,False
34,0 days 01:22:44.909000,ANT,12,NaT,13.0,4.0,NaT,0 days 01:15:48.952000,0 days 00:00:27.637000,NaT,...,True,Mercedes,0 days 01:14:10.463000,2026-03-07 06:01:29.175,152,NaN,False,,False,False
35,0 days 01:24:23.288000,ANT,12,NaT,14.0,5.0,0 days 01:22:44.909000,NaT,NaT,0 days 00:00:20.849000,...,False,Mercedes,0 days 01:22:44.909000,2026-03-07 06:10:03.621,1,NaN,False,,False,False
36,0 days 01:28:15.643000,ANT,12,NaT,15.0,5.0,NaT,0 days 01:25:58.949000,0 days 00:00:33.411000,0 days 00:00:25.690000,...,False,Mercedes,0 days 01:24:23.288000,2026-03-07 06:11:42.000,1,NaN,False,,False,False
37,0 days 01:29:52.554000,ANT,12,0 days 00:01:36.911000,16.0,6.0,0 days 01:28:18.391000,NaT,0 days 00:00:37.877000,0 days 00:00:19.532000,...,True,Mercedes,0 days 01:28:15.643000,2026-03-07 06:15:34.355,1,NaN,False,,False,False
38,0 days 01:31:11.365000,ANT,12,0 days 00:01:18.811000,17.0,6.0,NaT,NaT,0 days 00:00:27.556000,0 days 00:00:17.440000,...,True,Mercedes,0 days 01:29:52.554000,2026-03-07 06:17:11.266,1,NaN,False,,False,True
39,0 days 01:32:55.374000,ANT,12,NaT,18.0,6.0,NaT,0 days 01:32:55.374000,0 days 00:00:33.233000,0 days 00:00:24.050000,...,True,Mercedes,0 days 01:31:11.365000,2026-03-07 06:18:30.077,1,NaN,False,,False,False

In [8]:
lap_ant = session.laps.pick_drivers('ANT').pick_quicklaps().pick_fastest()
print(type(lap_ant))
print(lap_ant)
print(lap_ant['LapTime'])
print(type(lap_ant['LapTime']))

<class 'fastf1.core.Lap'>
Time                      0 days 01:31:11.365000
Driver                                       ANT
DriverNumber                                  12
LapTime                   0 days 00:01:18.811000
LapNumber                                   17.0
Stint                                        6.0
PitOutTime                                   NaT
PitInTime                                    NaT
Sector1Time               0 days 00:00:27.556000
Sector2Time               0 days 00:00:17.440000
Sector3Time               0 days 00:00:33.815000
Sector1SessionTime        0 days 01:30:20.110000
Sector2SessionTime        0 days 01:30:37.550000
Sector3SessionTime        0 days 01:31:11.365000
SpeedI1                                    272.0
SpeedI2                                    274.0
SpeedFL                                    298.0
SpeedST                                    289.0
IsPersonalBest                              True
Compound                                    SOFT
TyreLife                                     2.0
FreshTyre                                   True
Team                                    Mercedes
LapStartTime              0 days 01:29:52.554000
LapStartDate          2026-03-07 06:17:11.266000
TrackStatus                                    1
Position                                     NaN
Deleted                                    False
DeletedReason
FastF1Generated                            False
IsAccurate                                  True
Name: 38, dtype: object
0 days 00:01:18.811000
<class 'pandas._libs.tslibs.timedeltas.Timedelta'>

In [9]:
telem_ant = lap_ant.get_telemetry()

print(telem_ant.columns.tolist())
print("ANT Shape:", telem_ant.shape)
print("ANT Track Distance:", telem_ant['Distance'].max())
print("ANT Max Speed:", telem_ant['Speed'].max())
print("ANT Min Speed:", telem_ant['Speed'].min())

# telem_ant.head()
# telem_ant.tail()

['Date', 'SessionTime', 'DriverAhead', 'DistanceToDriverAhead', 'Time', 'RPM', 'Speed', 'nGear', 'Throttle', 'Brake', 'DRS', 'Source', 'Distance', 'RelativeDistance', 'Status', 'X', 'Y', 'Z']
ANT Shape: (555, 18)
ANT Track Distance: 5242.916368408636
ANT Max Speed: 324.0
ANT Min Speed: 97.0

In [10]:
lap_rus = session.laps.pick_drivers('RUS').pick_quicklaps().pick_fastest()

print("Antonelli's fastest lap:", lap_ant['LapTime'])
print("Russell's fastest lap:", lap_rus['LapTime'])

print(lap_ant['LapTime'].total_seconds() - lap_rus['LapTime'].total_seconds())

telem_rus = lap_rus.get_telemetry()

print(telem_rus.columns.tolist())
print("RUS Shape:", telem_rus.shape)
print("RUS Track Distance:", telem_rus['Distance'].max())
print("RUS Max Speed:", telem_rus['Speed'].max())
print("RUS Min Speed:", telem_rus['Speed'].min())

# telem_rus.head()
# telem_rus.tail()

Antonelli's fastest lap: 0 days 00:01:18.811000
Russell's fastest lap: 0 days 00:01:18.518000
0.29300000000000637
['Date', 'SessionTime', 'DriverAhead', 'DistanceToDriverAhead', 'Time', 'RPM', 'Speed', 'nGear', 'Throttle', 'Brake', 'DRS', 'Source', 'Distance', 'RelativeDistance', 'Status', 'X', 'Y', 'Z']
RUS Shape: (567, 18)
RUS Track Distance: 5233.247135913876
RUS Max Speed: 327.0
RUS Min Speed: 94.0

In [11]:
circuit_info = session.get_circuit_info()
print(circuit_info.corners)

              X             Y  Number Letter       Angle     Distance
0  -3650.594482   1193.784180       1        -176.632730   345.937862
1  -3555.053223   1992.750244       2          -1.517007   424.105272
2  -7194.970215   7101.942383       3         162.258315  1069.958382
3  -5878.734375   7709.864746       4         -23.426263  1220.216681
4  -5870.662598   9676.805664       5         159.215959  1428.533542
5  -2280.641357  11861.559570       6          96.736266  1858.303199
6  -1296.382446  11398.008789       7        -104.065903  1949.325516
7    502.412537  10576.311523       8          39.145642  2169.137459
8   2838.843750    798.959839       9        -101.197334  3268.158289
9   3973.896484    855.019897      10          73.476771  3378.107173
10  7489.130859  -4851.345215      11         -15.779635  4087.557885
11  5020.217773  -5538.887695      12        -106.082895  4345.597837
12  3587.226562  -3634.000000      13          89.839297  4597.213344
13  2300.284180  -4454.023438      14         -97.403246  4758.937266

In [19]:
import sys; sys.path.insert(0, '..')
from src.loaders import setup_cache, load_qualifying_session, get_fastest_valid_lap, get_lap_telemetry
from src.segments import resample_to_distance_grid, build_segments_from_corners

setup_cache()
session = load_qualifying_session(2026, 'Miami')
lap_ant = get_fastest_valid_lap(session, 'ANT')
print(lap_ant)
print(lap_ant['LapTime'])
telem_ant = get_lap_telemetry(lap_ant)
print(telem_ant.columns)
print(telem_ant.shape)

core           INFO 	Loading data for Miami Grand Prix - Qualifying [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '3', '16', '1', '63', '44', '81', '43', '10', '27', '30', '87', '55', '31', '23', '41', '14', '18', '77', '11', '5', '6']

Time                      0 days 01:09:44.552000
Driver                                       ANT
DriverNumber                                  12
LapTime                   0 days 00:01:27.798000
LapNumber                                   14.0
Stint                                        5.0
PitOutTime                                   NaT
PitInTime                                    NaT
Sector1Time               0 days 00:00:29.743000
Sector2Time               0 days 00:00:33.431000
Sector3Time               0 days 00:00:24.624000
Sector1SessionTime        0 days 01:08:46.497000
Sector2SessionTime        0 days 01:09:19.928000
Sector3SessionTime        0 days 01:09:44.552000
SpeedI1                                    222.0
SpeedI2                                    193.0
SpeedFL                                    267.0
SpeedST                                    325.0
IsPersonalBest                              True
Compound                                    SOFT
TyreLife                                     2.0
FreshTyre                                   True
Team                                    Mercedes
LapStartTime              0 days 01:08:16.754000
LapStartDate          2026-05-02 20:55:34.551000
TrackStatus                                    1
Position                                     NaN
Deleted                                    False
DeletedReason
FastF1Generated                            False
IsAccurate                                  True
Name: 13, dtype: object
0 days 00:01:27.798000
Index(['Date', 'SessionTime', 'DriverAhead', 'DistanceToDriverAhead', 'Time',
       'RPM', 'Speed', 'nGear', 'Throttle', 'Brake', 'DRS', 'Source',
       'Distance', 'RelativeDistance', 'Status', 'X', 'Y', 'Z'],
      dtype='object')
(641, 18)

In [22]:
session_miami = load_qualifying_session(2026, 'Miami')
circuit_info_miami = session_miami.get_circuit_info()
lap_ant_miami = get_fastest_valid_lap(session_miami, 'ANT')
telem_ant_miami = get_lap_telemetry(lap_ant)

core           INFO 	Loading data for Miami Grand Prix - Qualifying [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '3', '16', '1', '63', '44', '81', '43', '10', '27', '30', '87', '55', '31', '23', '41', '14', '18', '77', '11', '5', '6']

In [ ]:
segments = build_segments_from_corners(circuit_info_miami, telem_ant_miami['Distance'].max())

print(segments.shape)
print(segments['kind'].value_counts())

segments

(13, 4)
kind
straight    7
corner      6
Name: count, dtype: int64

  Segment      start_m        end_m      kind
0      S1     0.000000   315.942803  straight
1      C1   315.942803   614.970226    corner
2      S2   614.970226  1080.753343  straight
3      C2  1080.753343  1688.036932    corner
4      S3  1688.036932  2112.267265  straight